package com.bmc.buenacocinavendors.core

enum class OrderStatus(val status: String, val level: Int) {
    CREATED(ORDER_STATUS_CREATED_NAME, ORDER_STATUS_CREATED_LEVEL),
    ACTIVE(ORDER_STATUS_ACTIVE_NAME, ORDER_STATUS_ACTIVE_LEVEL),
    PROGRESS(ORDER_STATUS_PROGRESS_NAME, ORDER_STATUS_PROGRESS_LEVEL),
    ON_WAY(ORDER_STATUS_ON_WAY_NAME, ORDER_STATUS_ON_WAY_LEVEL),
    DELIVERED(ORDER_STATUS_DELIVERED_NAME, ORDER_STATUS_DELIVERED_LEVEL),
    ERROR(ORDER_STATUS_ERROR_NAME, ORDER_STATUS_ERROR_LEVEL),
    UNASSIGNED(ORDER_STATUS_UNASSIGNED_NAME, ORDER_STATUS_UNASSIGNED_LEVEL)
}